//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public string VIN { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> color { get; set; }
        public Nullable<int> TypeOfDriveId { get; set; }
        public Nullable<int> owner { get; set; }
        public Nullable<int> TypeOfEngineId { get; set; }
    
        public virtual Color Color1 { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual TypeOfDrive TypeOfDrive { get; set; }
        public virtual EngineType EngineType { get; set; }
    }
}
