//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Drivers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drivers()
        {
            this.Auto = new HashSet<Auto>();
            this.licence = new HashSet<licence>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string middlename { get; set; }
        public Nullable<double> passport_serial { get; set; }
        public Nullable<double> passport_number { get; set; }
        public Nullable<double> postcode { get; set; }
        public string address { get; set; }
        public string address_life { get; set; }
        public string company { get; set; }
        public string jobname { get; set; }
        public Nullable<double> phone { get; set; }
        public string email { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
        public byte[] photoBinary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auto> Auto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<licence> licence { get; set; }
        public licence CurrentLicence
        {
            get
            {
                return licence.FirstOrDefault();
            }
        }
    }
}
