//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DTP()
        {
            this.DTP_Photo = new HashSet<DTP_Photo>();
            this.Members_DTP = new HashSet<Members_DTP>();
        }
    
        public int Id { get; set; }
        public string Info { get; set; }
        public string Dies { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<System.DateTime> data_time { get; set; }
    
        public virtual Class_DTP Class_DTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTP_Photo> DTP_Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Members_DTP> Members_DTP { get; set; }
    }
}
