//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTP_Photo
    {
        public int id { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Id_DTP { get; set; }
    
        public virtual DTP DTP { get; set; }
    }
}
